name: Build KICODE for macOS

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
    - name: 1. Lay ma nguon tu Github ve máy ao
      uses: actions/checkout@v4 # Cập nhật lên v4 cho đồng bộ

    - name: 2. Cai dat moi truong Python
      uses: actions/setup-python@v5 # Cập nhật lên v5 mới nhất
      with:
        python-version: '3.10'

    - name: 3. Cai dat cac thu vien can thiet
      run: |
        pip install requests cryptography pyinstaller

    - name: 4. Dong goi phan mem bang PyInstaller
      run: |
        pyinstaller --onefile --windowed --add-data "logo.png:." --name="KICODE" kicode.py

    - name: 5. Nen thu muc KICODE.app thanh file .ZIP
      run: |
        cd dist
        zip -r KICODE_macOS.zip KICODE.app

    - name: 6. Day file zip len thanh qua (Artifact)
      uses: actions/upload-artifact@v4 # <<< ĐÃ SỬA: Cập nhật từ v3 lên v4 để hết lỗi
      with:
        name: KICODE_Mac_Installer
        path: dist/KICODE_macOS.zip
